name: Publish

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  release:
    name: Publish to NPM 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install

      - name: Build
        run: yarn build

      - run: yarn install --production

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
